name: test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - uses: actions/checkout@v2
      - run: make test
